export default {
  ActionButton: 'ActionButton',
  AppTitle: 'AppTitle',
  ErrorMessage: 'ErrorMessage',
  FloatingActions: 'FloatingActions',
  LayoutMain: 'LayoutMain',
  Loading: 'Loading',
  Settings: {
    content: 'Settings-content',
    content_view: 'Settings-content-view',
    content_edit: 'Settings-content-edit',
    content_item: 'Settings-content-item',
    actions: 'Settings-actions',
    actions_save: 'Settings-action-save',
    actions_undo: 'Settings-action-undo',
    actions_exit: 'Settings-action-exit',
    actions_edit: 'Settings-action-edit',
  },
  Topbar: 'Topbar',
  UserMenu: {
    button: 'UserMenu-button',
    flags: 'UserMenu-flags',
    menu: 'UserMenu-menu',
    settings: 'UserMenu-settings',
  },
};
