export default {
  ActionButton: 'ActionButton',
  AppTitle: 'AppTitle',
  ErrorMessage: 'ErrorMessage',
  Flags: {
    content_list_clear_search: 'Flags-content-menu-list-clear-search',
    content_list_placeholder: 'Flags-content-menu-list-placeholder',
    content_list_search: 'Flags-content-menu-list-search',
    content_list: 'Flags-content-menu-list',
    content_select: 'Flags-content-auto-select',
    content: 'Flags-content',
    modal_backdrop: 'Flags-modal-backdrop',
    modal_button_confirm_delete: 'Flags-modal-button-confirm_delete',
    modal_button_delete: 'Flags-modal-button-delete',
    modal_button_save: 'Flags-modal-button-save',
    modal_fab: 'Flags-modal-fab',
    modal_key: 'Flags-modal-key',
    modal_type: 'Flags-modal-type',
    modal_validation: 'Flags-modal-validation',
    modal: 'Flags-modal',
    pane_add: 'Flags-pane-add',
    pane_edit_add: 'Flags-pane-edit-add',
    pane_edit_environment: 'Flags-pane-edit-environment',
    pane_edit_remove: 'Flags-pane-edit-remove',
    pane_edit_save: 'Flags-pane-edit-save',
    pane_edit: 'Flags-pane-edit',
    panes: 'Flags-panes',
  },
  FloatingActions: 'FloatingActions',
  LayoutMain: 'LayoutMain',
  Loading: 'Loading',
  Settings: {
    actions_edit: 'Settings-action-edit',
    actions_exit: 'Settings-action-exit',
    actions_save: 'Settings-action-save',
    actions_undo: 'Settings-action-undo',
    actions: 'Settings-actions',
    content_edit: 'Settings-content-edit',
    content_item: 'Settings-content-item',
    content_view: 'Settings-content-view',
    content: 'Settings-content',
    edit_name: 'Settings-edit-name',
    edit_submit: 'Settings-edit-submit',
    edit_url: 'Settings-edit-url',
  },
  Topbar: 'Topbar',
  UserMenu: {
    button: 'UserMenu-button',
    flags: 'UserMenu-flags',
    menu: 'UserMenu-menu',
    settings: 'UserMenu-settings',
  },
};
